/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ingredient {
  'name' : string,
  'unit' : string,
  'category' : string,
}
export interface Recipe {
  'id' : bigint,
  'title' : string,
  'authorId' : Principal,
  'createdAt' : bigint,
  'cookTime' : bigint,
  'description' : string,
  'steps' : Array<string>,
  'imageUrl' : string,
  'prepTime' : bigint,
  'recipeIngredients' : Array<RecipeIngredient>,
  'category' : string,
  'servings' : bigint,
}
export interface RecipeIngredient {
  'name' : string,
  'unit' : string,
  'amount' : string,
}
export interface RegisteredUser {
  'principal' : Principal,
  'naam' : string,
  'email' : string,
  'mobile' : string,
  'registeredAt' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFavorite' : ActorMethod<[bigint], undefined>,
  'addIngredient' : ActorMethod<[Ingredient], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRecipe' : ActorMethod<[Recipe], bigint>,
  'deleteRecipe' : ActorMethod<[bigint], undefined>,
  'filterByCategory' : ActorMethod<[string], Array<Recipe>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<bigint>>,
  'getIngredient' : ActorMethod<[string], [] | [Ingredient]>,
  'getRecipe' : ActorMethod<[bigint], [] | [Recipe]>,
  'getRegisteredUsers' : ActorMethod<[], Array<RegisteredUser>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSeeds' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFavorite' : ActorMethod<[bigint], boolean>,
  'isUserRegistered' : ActorMethod<[], boolean>,
  'listIngredients' : ActorMethod<[], Array<Ingredient>>,
  'listRecipes' : ActorMethod<[], Array<Recipe>>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'removeFavorite' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchRecipes' : ActorMethod<[string], Array<Recipe>>,
  'updateRecipe' : ActorMethod<[bigint, Recipe], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];