/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Ingredient = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RecipeIngredient = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'amount' : IDL.Text,
});
export const Recipe = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'cookTime' : IDL.Nat,
  'description' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'prepTime' : IDL.Nat,
  'recipeIngredients' : IDL.Vec(RecipeIngredient),
  'category' : IDL.Text,
  'servings' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFavorite' : IDL.Func([IDL.Nat], [], []),
  'addIngredient' : IDL.Func([Ingredient], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRecipe' : IDL.Func([Recipe], [IDL.Nat], []),
  'deleteRecipe' : IDL.Func([IDL.Nat], [], []),
  'filterByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getIngredient' : IDL.Func([IDL.Text], [IDL.Opt(Ingredient)], ['query']),
  'getRecipe' : IDL.Func([IDL.Nat], [IDL.Opt(Recipe)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSeeds' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'listIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'listRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'removeFavorite' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchRecipes' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
  'updateRecipe' : IDL.Func([IDL.Nat, Recipe], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Ingredient = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RecipeIngredient = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'amount' : IDL.Text,
  });
  const Recipe = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'cookTime' : IDL.Nat,
    'description' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'prepTime' : IDL.Nat,
    'recipeIngredients' : IDL.Vec(RecipeIngredient),
    'category' : IDL.Text,
    'servings' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFavorite' : IDL.Func([IDL.Nat], [], []),
    'addIngredient' : IDL.Func([Ingredient], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRecipe' : IDL.Func([Recipe], [IDL.Nat], []),
    'deleteRecipe' : IDL.Func([IDL.Nat], [], []),
    'filterByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getIngredient' : IDL.Func([IDL.Text], [IDL.Opt(Ingredient)], ['query']),
    'getRecipe' : IDL.Func([IDL.Nat], [IDL.Opt(Recipe)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSeeds' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'listIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'listRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'removeFavorite' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchRecipes' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
    'updateRecipe' : IDL.Func([IDL.Nat, Recipe], [], []),
  });
};

export const init = ({ IDL }) => { return []; };